[program:speech-cache]
command=/bin/bash /workspace/speech-projector/scripts/run_job.sh -m speech_projector.cache --root /workspace/speech-projector/data --train-examples 1000 --batch-size 8
autostart=false
autorestart=false
stdout_logfile=/workspace/speech-projector/data/cache.log
stderr_logfile=/workspace/speech-projector/data/cache_error.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PROC_NAME="speech-cache"
