[program:speech-download-data]
command=/bin/bash /workspace/speech-projector/scripts/run_job.sh -m speech_projector.data --root /workspace/speech-projector/data --download-train 10000 --workers 4
autostart=false
autorestart=unexpected
startretries=5
stdout_logfile=/workspace/speech-projector/data/download.log
stderr_logfile=/workspace/speech-projector/data/download_error.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PROC_NAME="speech-download-data"
